@TodoList.Gateway_HostAddress =

GET http://localhost:6000/todo/
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU1NjA4NDg0ODM0RTA1NjQ2NDI2QkI2RkYyRjRBNzcyIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJuYmYiOjE3MDY2NTczMTcsImlhdCI6MTcwNjY1NzMxNywiZXhwIjoxNzA5MjQ5MzE3LCJzY29wZSI6WyJ0b2RvQXBwIl0sImNsaWVudF9pZCI6InRvZG9BcHAiLCJqdGkiOiIyQUE3RTkyMDNFNTlGQURBMEI3NUM0MTUzQ0Y5OTIyRiJ9.n-a7IEfIlI6NfTEfEHELZHQVpontWLjKUsIbUmRTBI0yF1lCiUgxlnP88lrHCQmL0kB1n1WDQ_J6Pq1qEb6TfzjTtSnPKrpN3mF1alOpnXupV5Gql6gh_KNIr8FAOLuUot0vMQ5AoiqS5IE2SYQRKlTIKstc2S7a5id93xFkiUiLYB4cc-UGfHSMexGlQmqCpVb-3Cuqdn1k2SJoFQYqucXpvOR4GZbnm9OJlsqhbMuw1nPtDvQ7duK02jTg1328bZRL9h3Z5epAEvXoHZvhE8iDSThoon4WkToPfBlcU1w77cSQb5SjL1w4-xB8ykq_YYEnu189_njtZ7lhsROxhw

### s ssss
GET http://localhost:6000/todo/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU1NjA4NDg0ODM0RTA1NjQ2NDI2QkI2RkYyRjRBNzcyIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJuYmYiOjE3MDY2Njc5MzIsImlhdCI6MTcwNjY2NzkzMiwiZXhwIjoxNzA2NjY4MjkyLCJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIiwidG9kb0FwcCJdLCJhbXIiOlsicHdkIl0sImNsaWVudF9pZCI6InRvZG9BcHAiLCJzdWIiOiJhMTJjMWFiMi0zMzQzLTQ4MGYtODdlYy02MmE4NDU4NzVkMmQiLCJhdXRoX3RpbWUiOjE3MDY2Njc5MzIsImlkcCI6ImxvY2FsIiwidXNlcm5hbWUiOiJ5YWdvIiwibmFtZSI6IllhZ28gZGEgU2lsdmEiLCJqdGkiOiJCNkQ2MkE4REJBRkI1Mjc3MjI1M0MzRUVDMjlFOTRDNSJ9.cj11Uc0r4Zx5MmzKGhc_RW8jiXNBlyGzZX_gmhZFG3AXXIToJSqcXdVtTymlM_k9MnqnmiDbxPHyZ94lTYCWvkZYYANHvmSGE0mgqz6cADYBZYy4lG-8SE01osQxg46WBSOShuUHDPx3TrrniJUoG9LDOl2JQ0W4zjmKwSLcp3alcxaCnhULAfvNhcWd12C30FB7VaSf4gDo5GqbmrCPio4AurRiHFJ0pVvDwFi0HIP2PQPZ4Suk4ACwSLtqMEpF2Ay7xrU0jT1KNmcaQWUzHp-aPscOtourTkaymtJPTLE_wVbJ1-jy6nxQ7GWTNhGTaphosCMj7ogAKXeIY6USSQ

