@TodoList.Gateway_HostAddress =

GET http://localhost:6000/todo/
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkQ3MjEwNjBGODdDNEJGOTVFMTA5MDVFRjlEQ0ExQzE4IiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJpZGVudGl0eS1zdmMiLCJuYmYiOjE3MDcyNDQ0MzgsImlhdCI6MTcwNzI0NDQzOCwiZXhwIjoxNzA3MjQ0Nzk4LCJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIiwidG9kb0FwcCJdLCJhbXIiOlsicHdkIl0sImNsaWVudF9pZCI6InRvZG9BcHAiLCJzdWIiOiI5ZjRhNTkwMS0wYmVlLTQ4ZjctYWI5OS05Y2YxNjFiOWMwNzMiLCJhdXRoX3RpbWUiOjE3MDcyNDQ0MzgsImlkcCI6ImxvY2FsIiwidXNlcm5hbWUiOiJ5YWdvb2xpdmVyIiwibmFtZSI6IllhZ28gT2xpdmVpcmEgZGEgU2lsdmEiLCJqdGkiOiI0ODA3OEI4OEEzNzU3RjNGQzdBNEMwMTBFQkM0OThBOSJ9.S1T1lEdCTngvNTldu19S6Msm_msFRhLaHp-pW1NyB2mI4OaQQJJTXMSTvinynG7UKgtv8ExV9j397G1j-P7MluepWR6VyxQu82Qc0DO1G8IZPB2sTUclMF5u5uJCJV0vUegE9klOn8CGSXHuPhojzrSeAu6LJLTGOQhXmHCgcUfsbV1Qy6mRcbx1kLeLfYD0dn-pl6IhmKc-gJhGuA248w7GDIG32_k7XaRF0XGUkyqJiEA6lr17X197jm3DdSSDpB1fQmtFWGYeFNYvwMSGiqbKFL5DJ0wdSGLxVP4_3vF6g0FpRMSnb9hsCs5KV2UDuwtUVSnvQDUQoX0CVvYWVg

### s ssss
GET http://localhost:6000/todo/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkQ3MjEwNjBGODdDNEJGOTVFMTA5MDVFRjlEQ0ExQzE4IiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJpZGVudGl0eS1zdmMiLCJuYmYiOjE3MDcyNDQ0MzgsImlhdCI6MTcwNzI0NDQzOCwiZXhwIjoxNzA3MjQ0Nzk4LCJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIiwidG9kb0FwcCJdLCJhbXIiOlsicHdkIl0sImNsaWVudF9pZCI6InRvZG9BcHAiLCJzdWIiOiI5ZjRhNTkwMS0wYmVlLTQ4ZjctYWI5OS05Y2YxNjFiOWMwNzMiLCJhdXRoX3RpbWUiOjE3MDcyNDQ0MzgsImlkcCI6ImxvY2FsIiwidXNlcm5hbWUiOiJ5YWdvb2xpdmVyIiwibmFtZSI6IllhZ28gT2xpdmVpcmEgZGEgU2lsdmEiLCJqdGkiOiI0ODA3OEI4OEEzNzU3RjNGQzdBNEMwMTBFQkM0OThBOSJ9.S1T1lEdCTngvNTldu19S6Msm_msFRhLaHp-pW1NyB2mI4OaQQJJTXMSTvinynG7UKgtv8ExV9j397G1j-P7MluepWR6VyxQu82Qc0DO1G8IZPB2sTUclMF5u5uJCJV0vUegE9klOn8CGSXHuPhojzrSeAu6LJLTGOQhXmHCgcUfsbV1Qy6mRcbx1kLeLfYD0dn-pl6IhmKc-gJhGuA248w7GDIG32_k7XaRF0XGUkyqJiEA6lr17X197jm3DdSSDpB1fQmtFWGYeFNYvwMSGiqbKFL5DJ0wdSGLxVP4_3vF6g0FpRMSnb9hsCs5KV2UDuwtUVSnvQDUQoX0CVvYWVg

