apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: yagooliverce/gateway
        imagePullPolicy: Always
        env:
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:80
          - name: ASPNETCORE_ENVIRONMENT
            value: Docker
          - name: IdentityServiceUrl
            value: http://identity-svc
          - name: ElasticConfiguration__Uri
            value: http://elasticsearch:9200
          - name: ReverseProxy__Clusters__todocluster__Destinations__todoApi__Address
            value: http://todo-service
          - name: ReverseProxy__Routes__todolist__ClusterId
            value: todocluster
          - name: ReverseProxy__Routes__todolist__AuthorizationPolicy
            value: default
          - name: ReverseProxy__Routes__todolist__Match__Path
            value: /todo/{**catch-all}
          - name: ReverseProxy__Routes__todolist__Match__Methods
            value: POST,PUT,DELETE,GET
          - name: ReverseProxy__Routes__todolist__Transforms__0__PathPattern
            value: api/item/{**catch-all}
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-clusterip
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 80