apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
spec:
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
      - name: identity
        image: yagooliverce/todo-service
        imagePullPolicy: Always
        env:
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:80
          - name: ASPNETCORE_ENVIRONMENT
            value: Docker
          - name: IdentityServiceUrl
            value: http://identity-svc
          - name: ElasticConfiguration__Uri
            value: http://elasticsearch:9200
          - name: ConnectionStrings__TodoList
            value: Server=postgres-db,5432;User Id=postgres;Password=dev1234;Database=todolist
---
apiVersion: v1
kind: Service
metadata:
  name: todo-clusterip
spec:
  type: ClusterIP
  selector:
    app: todo-service
  ports:
  - port: 80
    targetPort: 80